/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as ResetPasswordConfirmRouteImport } from './routes/reset-password-confirm'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AvisoDePrivacidadRouteImport } from './routes/aviso-de-privacidad'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViajesIndexRouteImport } from './routes/viajes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ViajesProximosRouteImport } from './routes/viajes/proximos'
import { Route as ViajesPasadosRouteImport } from './routes/viajes/pasados'
import { Route as ViajesViajeIdRouteImport } from './routes/viajes/$viajeId'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminReseChar241asRouteImport } from './routes/admin/reseñas'
import { Route as AdminReservacionesRouteImport } from './routes/admin/reservaciones'
import { Route as AdminAjustesRouteImport } from './routes/admin/ajustes'
import { Route as AdminViajesIndexRouteImport } from './routes/admin/viajes/index'
import { Route as AdminViajesNuevoRouteImport } from './routes/admin/viajes/nuevo'
import { Route as AdminViajesViajeIdEditarRouteImport } from './routes/admin/viajes/$viajeId/editar'

const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordConfirmRoute = ResetPasswordConfirmRouteImport.update({
  id: '/reset-password-confirm',
  path: '/reset-password-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadRoute = AvisoDePrivacidadRouteImport.update({
  id: '/aviso-de-privacidad',
  path: '/aviso-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesIndexRoute = ViajesIndexRouteImport.update({
  id: '/viajes/',
  path: '/viajes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ViajesProximosRoute = ViajesProximosRouteImport.update({
  id: '/viajes/proximos',
  path: '/viajes/proximos',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesPasadosRoute = ViajesPasadosRouteImport.update({
  id: '/viajes/pasados',
  path: '/viajes/pasados',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesViajeIdRoute = ViajesViajeIdRouteImport.update({
  id: '/viajes/$viajeId',
  path: '/viajes/$viajeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReseChar241asRoute = AdminReseChar241asRouteImport.update({
  id: '/reseñas',
  path: '/reseñas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservacionesRoute = AdminReservacionesRouteImport.update({
  id: '/reservaciones',
  path: '/reservaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAjustesRoute = AdminAjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViajesIndexRoute = AdminViajesIndexRouteImport.update({
  id: '/viajes/',
  path: '/viajes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViajesNuevoRoute = AdminViajesNuevoRouteImport.update({
  id: '/viajes/nuevo',
  path: '/viajes/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminViajesViajeIdEditarRoute =
  AdminViajesViajeIdEditarRouteImport.update({
    id: '/viajes/$viajeId/editar',
    path: '/viajes/$viajeId/editar',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/contacto': typeof ContactoRoute
  '/creditos': typeof CreditosRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-confirm': typeof ResetPasswordConfirmRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/reservaciones': typeof AdminReservacionesRoute
  '/admin/reseñas': typeof AdminReseChar241asRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/viajes/$viajeId': typeof ViajesViajeIdRoute
  '/viajes/pasados': typeof ViajesPasadosRoute
  '/viajes/proximos': typeof ViajesProximosRoute
  '/admin/': typeof AdminIndexRoute
  '/viajes': typeof ViajesIndexRoute
  '/admin/viajes/nuevo': typeof AdminViajesNuevoRoute
  '/admin/viajes': typeof AdminViajesIndexRoute
  '/admin/viajes/$viajeId/editar': typeof AdminViajesViajeIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/contacto': typeof ContactoRoute
  '/creditos': typeof CreditosRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-confirm': typeof ResetPasswordConfirmRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/reservaciones': typeof AdminReservacionesRoute
  '/admin/reseñas': typeof AdminReseChar241asRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/viajes/$viajeId': typeof ViajesViajeIdRoute
  '/viajes/pasados': typeof ViajesPasadosRoute
  '/viajes/proximos': typeof ViajesProximosRoute
  '/admin': typeof AdminIndexRoute
  '/viajes': typeof ViajesIndexRoute
  '/admin/viajes/nuevo': typeof AdminViajesNuevoRoute
  '/admin/viajes': typeof AdminViajesIndexRoute
  '/admin/viajes/$viajeId/editar': typeof AdminViajesViajeIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/contacto': typeof ContactoRoute
  '/creditos': typeof CreditosRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reset-password-confirm': typeof ResetPasswordConfirmRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/ajustes': typeof AdminAjustesRoute
  '/admin/reservaciones': typeof AdminReservacionesRoute
  '/admin/reseñas': typeof AdminReseChar241asRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/viajes/$viajeId': typeof ViajesViajeIdRoute
  '/viajes/pasados': typeof ViajesPasadosRoute
  '/viajes/proximos': typeof ViajesProximosRoute
  '/admin/': typeof AdminIndexRoute
  '/viajes/': typeof ViajesIndexRoute
  '/admin/viajes/nuevo': typeof AdminViajesNuevoRoute
  '/admin/viajes/': typeof AdminViajesIndexRoute
  '/admin/viajes/$viajeId/editar': typeof AdminViajesViajeIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-de-privacidad'
    | '/contacto'
    | '/creditos'
    | '/galeria'
    | '/login'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/reset-password'
    | '/reset-password-confirm'
    | '/terminos-y-condiciones'
    | '/admin/ajustes'
    | '/admin/reservaciones'
    | '/admin/reseñas'
    | '/admin/usuarios'
    | '/viajes/$viajeId'
    | '/viajes/pasados'
    | '/viajes/proximos'
    | '/admin/'
    | '/viajes'
    | '/admin/viajes/nuevo'
    | '/admin/viajes'
    | '/admin/viajes/$viajeId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidad'
    | '/contacto'
    | '/creditos'
    | '/galeria'
    | '/login'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/reset-password'
    | '/reset-password-confirm'
    | '/terminos-y-condiciones'
    | '/admin/ajustes'
    | '/admin/reservaciones'
    | '/admin/reseñas'
    | '/admin/usuarios'
    | '/viajes/$viajeId'
    | '/viajes/pasados'
    | '/viajes/proximos'
    | '/admin'
    | '/viajes'
    | '/admin/viajes/nuevo'
    | '/admin/viajes'
    | '/admin/viajes/$viajeId/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-de-privacidad'
    | '/contacto'
    | '/creditos'
    | '/galeria'
    | '/login'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/reset-password'
    | '/reset-password-confirm'
    | '/terminos-y-condiciones'
    | '/admin/ajustes'
    | '/admin/reservaciones'
    | '/admin/reseñas'
    | '/admin/usuarios'
    | '/viajes/$viajeId'
    | '/viajes/pasados'
    | '/viajes/proximos'
    | '/admin/'
    | '/viajes/'
    | '/admin/viajes/nuevo'
    | '/admin/viajes/'
    | '/admin/viajes/$viajeId/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoDePrivacidadRoute: typeof AvisoDePrivacidadRoute
  ContactoRoute: typeof ContactoRoute
  CreditosRoute: typeof CreditosRoute
  GaleriaRoute: typeof GaleriaRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResetPasswordConfirmRoute: typeof ResetPasswordConfirmRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  ViajesViajeIdRoute: typeof ViajesViajeIdRoute
  ViajesPasadosRoute: typeof ViajesPasadosRoute
  ViajesProximosRoute: typeof ViajesProximosRoute
  ViajesIndexRoute: typeof ViajesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password-confirm': {
      id: '/reset-password-confirm'
      path: '/reset-password-confirm'
      fullPath: '/reset-password-confirm'
      preLoaderRoute: typeof ResetPasswordConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidad': {
      id: '/aviso-de-privacidad'
      path: '/aviso-de-privacidad'
      fullPath: '/aviso-de-privacidad'
      preLoaderRoute: typeof AvisoDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/': {
      id: '/viajes/'
      path: '/viajes'
      fullPath: '/viajes'
      preLoaderRoute: typeof ViajesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/viajes/proximos': {
      id: '/viajes/proximos'
      path: '/viajes/proximos'
      fullPath: '/viajes/proximos'
      preLoaderRoute: typeof ViajesProximosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/pasados': {
      id: '/viajes/pasados'
      path: '/viajes/pasados'
      fullPath: '/viajes/pasados'
      preLoaderRoute: typeof ViajesPasadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/$viajeId': {
      id: '/viajes/$viajeId'
      path: '/viajes/$viajeId'
      fullPath: '/viajes/$viajeId'
      preLoaderRoute: typeof ViajesViajeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reseñas': {
      id: '/admin/reseñas'
      path: '/reseñas'
      fullPath: '/admin/reseñas'
      preLoaderRoute: typeof AdminReseChar241asRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservaciones': {
      id: '/admin/reservaciones'
      path: '/reservaciones'
      fullPath: '/admin/reservaciones'
      preLoaderRoute: typeof AdminReservacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ajustes': {
      id: '/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AdminAjustesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/viajes/': {
      id: '/admin/viajes/'
      path: '/viajes'
      fullPath: '/admin/viajes'
      preLoaderRoute: typeof AdminViajesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/viajes/nuevo': {
      id: '/admin/viajes/nuevo'
      path: '/viajes/nuevo'
      fullPath: '/admin/viajes/nuevo'
      preLoaderRoute: typeof AdminViajesNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/viajes/$viajeId/editar': {
      id: '/admin/viajes/$viajeId/editar'
      path: '/viajes/$viajeId/editar'
      fullPath: '/admin/viajes/$viajeId/editar'
      preLoaderRoute: typeof AdminViajesViajeIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAjustesRoute: typeof AdminAjustesRoute
  AdminReservacionesRoute: typeof AdminReservacionesRoute
  AdminReseChar241asRoute: typeof AdminReseChar241asRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminViajesNuevoRoute: typeof AdminViajesNuevoRoute
  AdminViajesIndexRoute: typeof AdminViajesIndexRoute
  AdminViajesViajeIdEditarRoute: typeof AdminViajesViajeIdEditarRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAjustesRoute: AdminAjustesRoute,
  AdminReservacionesRoute: AdminReservacionesRoute,
  AdminReseChar241asRoute: AdminReseChar241asRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminViajesNuevoRoute: AdminViajesNuevoRoute,
  AdminViajesIndexRoute: AdminViajesIndexRoute,
  AdminViajesViajeIdEditarRoute: AdminViajesViajeIdEditarRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoDePrivacidadRoute: AvisoDePrivacidadRoute,
  ContactoRoute: ContactoRoute,
  CreditosRoute: CreditosRoute,
  GaleriaRoute: GaleriaRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResetPasswordConfirmRoute: ResetPasswordConfirmRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  ViajesViajeIdRoute: ViajesViajeIdRoute,
  ViajesPasadosRoute: ViajesPasadosRoute,
  ViajesProximosRoute: ViajesProximosRoute,
  ViajesIndexRoute: ViajesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
