/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as PreguntasFrecuentesRouteImport } from './routes/preguntas-frecuentes'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AvisoDePrivacidadRouteImport } from './routes/aviso-de-privacidad'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViajesIndexRouteImport } from './routes/viajes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ViajesProximosRouteImport } from './routes/viajes/proximos'
import { Route as ViajesPasadosRouteImport } from './routes/viajes/pasados'
import { Route as ViajesViajeIdRouteImport } from './routes/viajes/$viajeId'
import { Route as AdminTripsRouteImport } from './routes/admin/trips'

const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasFrecuentesRoute = PreguntasFrecuentesRouteImport.update({
  id: '/preguntas-frecuentes',
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadRoute = AvisoDePrivacidadRouteImport.update({
  id: '/aviso-de-privacidad',
  path: '/aviso-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesIndexRoute = ViajesIndexRouteImport.update({
  id: '/viajes/',
  path: '/viajes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ViajesProximosRoute = ViajesProximosRouteImport.update({
  id: '/viajes/proximos',
  path: '/viajes/proximos',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesPasadosRoute = ViajesPasadosRouteImport.update({
  id: '/viajes/pasados',
  path: '/viajes/pasados',
  getParentRoute: () => rootRouteImport,
} as any)
const ViajesViajeIdRoute = ViajesViajeIdRouteImport.update({
  id: '/viajes/$viajeId',
  path: '/viajes/$viajeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/contacto': typeof ContactoRoute
  '/creditos': typeof CreditosRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/trips': typeof AdminTripsRoute
  '/viajes/$viajeId': typeof ViajesViajeIdRoute
  '/viajes/pasados': typeof ViajesPasadosRoute
  '/viajes/proximos': typeof ViajesProximosRoute
  '/admin/': typeof AdminIndexRoute
  '/viajes': typeof ViajesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/contacto': typeof ContactoRoute
  '/creditos': typeof CreditosRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/trips': typeof AdminTripsRoute
  '/viajes/$viajeId': typeof ViajesViajeIdRoute
  '/viajes/pasados': typeof ViajesPasadosRoute
  '/viajes/proximos': typeof ViajesProximosRoute
  '/admin': typeof AdminIndexRoute
  '/viajes': typeof ViajesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/contacto': typeof ContactoRoute
  '/creditos': typeof CreditosRoute
  '/galeria': typeof GaleriaRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/admin/trips': typeof AdminTripsRoute
  '/viajes/$viajeId': typeof ViajesViajeIdRoute
  '/viajes/pasados': typeof ViajesPasadosRoute
  '/viajes/proximos': typeof ViajesProximosRoute
  '/admin/': typeof AdminIndexRoute
  '/viajes/': typeof ViajesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-de-privacidad'
    | '/contacto'
    | '/creditos'
    | '/galeria'
    | '/login'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/terminos-y-condiciones'
    | '/admin/trips'
    | '/viajes/$viajeId'
    | '/viajes/pasados'
    | '/viajes/proximos'
    | '/admin/'
    | '/viajes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidad'
    | '/contacto'
    | '/creditos'
    | '/galeria'
    | '/login'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/terminos-y-condiciones'
    | '/admin/trips'
    | '/viajes/$viajeId'
    | '/viajes/pasados'
    | '/viajes/proximos'
    | '/admin'
    | '/viajes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-de-privacidad'
    | '/contacto'
    | '/creditos'
    | '/galeria'
    | '/login'
    | '/nosotros'
    | '/preguntas-frecuentes'
    | '/terminos-y-condiciones'
    | '/admin/trips'
    | '/viajes/$viajeId'
    | '/viajes/pasados'
    | '/viajes/proximos'
    | '/admin/'
    | '/viajes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AvisoDePrivacidadRoute: typeof AvisoDePrivacidadRoute
  ContactoRoute: typeof ContactoRoute
  CreditosRoute: typeof CreditosRoute
  GaleriaRoute: typeof GaleriaRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  ViajesViajeIdRoute: typeof ViajesViajeIdRoute
  ViajesPasadosRoute: typeof ViajesPasadosRoute
  ViajesProximosRoute: typeof ViajesProximosRoute
  ViajesIndexRoute: typeof ViajesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidad': {
      id: '/aviso-de-privacidad'
      path: '/aviso-de-privacidad'
      fullPath: '/aviso-de-privacidad'
      preLoaderRoute: typeof AvisoDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/': {
      id: '/viajes/'
      path: '/viajes'
      fullPath: '/viajes'
      preLoaderRoute: typeof ViajesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/viajes/proximos': {
      id: '/viajes/proximos'
      path: '/viajes/proximos'
      fullPath: '/viajes/proximos'
      preLoaderRoute: typeof ViajesProximosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/pasados': {
      id: '/viajes/pasados'
      path: '/viajes/pasados'
      fullPath: '/viajes/pasados'
      preLoaderRoute: typeof ViajesPasadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viajes/$viajeId': {
      id: '/viajes/$viajeId'
      path: '/viajes/$viajeId'
      fullPath: '/viajes/$viajeId'
      preLoaderRoute: typeof ViajesViajeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminTripsRoute: typeof AdminTripsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminTripsRoute: AdminTripsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AvisoDePrivacidadRoute: AvisoDePrivacidadRoute,
  ContactoRoute: ContactoRoute,
  CreditosRoute: CreditosRoute,
  GaleriaRoute: GaleriaRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  ViajesViajeIdRoute: ViajesViajeIdRoute,
  ViajesPasadosRoute: ViajesPasadosRoute,
  ViajesProximosRoute: ViajesProximosRoute,
  ViajesIndexRoute: ViajesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
